def  cartas(row):
    if row.opening is  None:
        row.opening=''
    if row.closing is  None:
        row.closing=''

    latexfile='\n'
    latexfile=latexfile+'%'+row.description+'\n'
    latexfile=latexfile+r'\documentclass{letter}'+'\n'
    latexfile=latexfile+r'\usepackage[utf8]{inputenc}'+'\n'
    latexfile=latexfile+row.preamble+'\n'
    latexfile=latexfile+row.address+'\n'
    latexfile=latexfile+r'\signature{'+row.common_signature+'}\n'
    latexfile=latexfile+r'\begin{document}'+'\n'
    latexfile=latexfile+r'\begin{letter}{'+row.para+'}\n'
    latexfile=latexfile+r'\opening{'+row.opening+'}\n'
    latexfile=latexfile+row.body+'\n'
    latexfile=latexfile+r'\closing{'+row.closing+'}\n'
    latexfile=latexfile+r'\end{letter}'+'\n'
    latexfile=latexfile+r'\end{document}'+'\n'
    
    return latexfile

def seminarios(row):
    import calendar
    latexfile='\n'
    latexfile=latexfile+r'\documentclass[xcolor=pdftex,dvipsnames,table]{beamer}'+'\n'
    latexfile=latexfile+r'\pdfoutput=1'+'\n'
    latexfile=latexfile+r'\mode<presentation>'+'\n'
    latexfile=latexfile+r'{'+'\n'
    latexfile=latexfile+r'  \setbeamercovered{transparent}'+'\n'
    latexfile=latexfile+r'  \setbeamertemplate{blocks}[rounded][shadow=true]'+'\n'
    latexfile=latexfile+r'  \setbeamertemplate{navigation symbols}{}'+'\n'
    latexfile=latexfile+r'  \setbeamertemplate{footline}{%\hspace*{.5cm}'+'\n'
    latexfile=latexfile+r'    \scriptsize{\phantom{Gg}%\insertauthor'+'\n' 
    latexfile=latexfile+r'      \hspace*{50pt}'+'\n'
    latexfile=latexfile+r'      \hfill \insertframenumber'+'\n'
    latexfile=latexfile+r'      \hspace*{.5cm}}}'+'\n'
    latexfile=latexfile+r'}'+'\n'
    latexfile=latexfile+r'\usepackage[T1]{fontenc}'+'\n'
    latexfile=latexfile+r'\usepackage[utf8]{inputenc}'+'\n'
    latexfile=latexfile+r'\usepackage[spanish]{babel}'+'\n'
    latexfile=latexfile+r'\spanishdecimal{.}'+'\n'
    latexfile=latexfile+r'\usepackage{beamerprosper}'+'\n'
    latexfile=latexfile+r'\usepackage{amsmath,amssymb}'+'\n'
    latexfile=latexfile+r'\usepackage{graphicx}'+'\n'
    latexfile=latexfile+r'\usepackage{mycolors}'+'\n'
    latexfile=latexfile+r'\usepackage{pgf}'+'\n'
    latexfile=latexfile+r'\setlength{\textwidth}{120 mm}'+'\n'
    latexfile=latexfile+r'\setbeamersize{text margin left=10pt,text margin right=10pt}'+'\n'
    latexfile=latexfile+r'\newcommand{\widescreen}{'+'\n'
    latexfile=latexfile+r'\setlength{\paperwidth}{171 mm}'+'\n'
    latexfile=latexfile+r'\setlength{\paperheight}{96 mm}'+'\n'
    latexfile=latexfile+r'\setlength{\textwidth}{161 mm}'+'\n'
    latexfile=latexfile+r'\setlength{\textheight}{86 mm}'+'\n'
    latexfile=latexfile+r'}'+'\n'
    latexfile=latexfile+r'\begin{document}'+'\n'
    latexfile=latexfile+r'\setbeamertemplate{background}{\includegraphics[width=\paperwidth]{gfifseminars}}'+'\n'
    latexfile=latexfile+r'\begin{frame}[plain]'+'\n'
    latexfile=latexfile+r'\begin{picture}(320,250)'+'\n'
    latexfile=latexfile+r'\put(0,210){'+'\n'
    latexfile=latexfile+r'\begin{minipage}[t]{1.0\linewidth}'+'\n'
    latexfile=latexfile+r'\begin{center}'+'\n'
    latexfile=latexfile+r'\textbf{\color{red}\large'+'\n'
    latexfile=latexfile+row.title+'}\\\\'+'\n'
    latexfile=latexfile+r'\textbf{\color{blue}\small '+row['name']+'}\\\\'+'\n'
    latexfile=latexfile+r'\textbf{\color{blue}\scriptsize '+row.institution+'}\\\\'+'\n'
    latexfile=latexfile+r'\textbf{\color{blue}\footnotesize{Resumen:}}'+'\n'
    latexfile=latexfile+r'\end{center}'+'\n'
    latexfile=latexfile+r'\end{minipage}'+'\n'
    latexfile=latexfile+r'}%'+'\n'
    latexfile=latexfile+r'    \put(0,140){'+'\n'
    latexfile=latexfile+r'  \begin{minipage}[t]{1.0\linewidth}'+'\n'
    latexfile=latexfile+r'   \footnotesize'+'\n'
    latexfile=latexfile+row.abstract+'\n'
    latexfile=latexfile+r'\end{minipage}'+'\n'
    latexfile=latexfile+r'}'+'\n'
    latexfile=latexfile+r'\put(0,0){'+'\n'
    latexfile=latexfile+r'  \begin{minipage}[t]{1.0\linewidth}'+'\n'
    latexfile=latexfile+r'\parbox{0.2\textwidth}{\textbf{\color{red}\scriptsize Lugar: '+row.lugar+'}}%'+'\n'
    latexfile=latexfile+r'\parbox{0.6\textwidth}{\centering{\textbf{\color{red}\scriptsize '+'\n'
    latexfile=latexfile+r'Fecha: '+calendar.day_name[row.fecha.weekday()]+' '+'{}'.format(row.fecha.day)+', '+'{}'.format(row.fecha.year)+'}}}%'+'\n'
    latexfile=latexfile+r'\parbox{0.2\textwidth}{\raggedleft{\textbf{\color{red}\scriptsize Hora: '+row.hora+'}}}%'+'\n'
    latexfile=latexfile+r'  \end{minipage}'+'\n'
    latexfile=latexfile+r'}% '+'\n'   
    latexfile=latexfile+r'\end{picture}'+'\n'
    latexfile=latexfile+r'\end{frame}'+'\n'
    latexfile=latexfile+r'\end{document}'+'\n'        
    
    return latexfile